version: 1

tools:
  - name: rustfmt
    include: ["**/*.rs"]
    cmd: cargo
    args: [fmt, --]
    check_args: [fmt, --, --check]

  - name: prettier
    include:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"
    exclude:
      - "target/**"
    cmd: npx
    args: [prettier, --write]
    check_args: [prettier, --check]
